### ISSUE TITLE
tensorize_icu throws AttributeError: Can only use .str accessor with string values!

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1137]
## Error message or warning
```
2021-01-09 00:47:47 - INFO - tensorizer:177 - Tensorized data from MRN 123, CSN 567 into /home/erikr/icu-temp/results_temp/123.hd5.
2021-01-09 00:48:11 - INFO - tensorizer:177 - Tensorized data from MRN 123, CSN 978 into /home/erikr/icu-temp/results_temp/123.hd5.
2021-01-09 00:48:11 - ERROR - recipes:89 - Can only use .str accessor with string values!
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/tensorizer.py", line 184, in _main_write
    raise error
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/tensorizer.py", line 175, in _main_write
    self._write_edw_data(self.edw, mrn, visit_id, writer=writer)
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/tensorizer.py", line 256, in _write_edw_data
    vitals = reader.list_vitals()
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/readers.py", line 200, in list_vitals
    return list(vitals_df[signal_column].str.upper().unique())
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5456, in __getattr__
    return object.__getattribute__(self, name)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/accessor.py", line 180, in __get__
    accessor_obj = self._accessor(obj)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/strings/accessor.py", line 154, in __init__
    self._inferred_dtype = self._validate(data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/strings/accessor.py", line 218, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!
"""
```

## Expected behavior
No error.

## Possible solution
TBD

## Steps to reproduce
```
./scripts/run.sh $PWD/ml4c3/recipes.py tensorize_icu_no_edw_pull \
--num_workers 10 \
--adt /media/ml4c3/cohorts_lists/adt_cabg.csv \
--xref /media/ml4c3/cohorts_lists/xref_cabg.csv \
--alarms /media/ml4c3/bedmaster_alarms \
--mrn_start_index 1501 \
--mrn_end_index 2000 \
--tensors /media/ml4c3/hd5_cabg_$YOUR_INITIALS \
--staging_dir ~/icu-temp \
--staging_batch_size 10 \
--allow_one_source \
--overwrite
```

**Comment by erikr** [comment]
@RogerPallares tensorize finally threw the error again. I added the log and args to [`~/dropbox/bedmaster-data-qc/tensorize-throws-attr-error`](https://www.dropbox.com/sh/5jijlkb7qg30m0s/AABW_llQOO_Gh6hNUqIvA7vEa?dl=0).
