### ISSUE TITLE
Tensorize fresh CABG and Arrest cohort

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1147]
## Blocked by or pending
#1137
#1142

**Comment by erikr** [comment]
@RogerPallares is this still blocked? What is the status of this, and how can others help?

**Comment by RogerPallares** [comment]
Once the script that is running @raimonpv to modify the date of the flowsheets is finished we can start tensorizing again, it should be finished by tonight. I already created the xref table for both cabg and arrests, we only need to run the command with the indices on the issue.

**Comment by StevenSong** [comment]
@RogerPallares @raimonpv should syntax point to other edw folder or will /media/ml4c3/edw be overwritten?

**Comment by raimonpv** [comment]
It should be ready to go. Some of the files might still have the wrong format as I ran again the dedup script and closed while it was in the middle few times. But I'll try to fix that before anyone encounters one of these patients.

**Comment by RogerPallares** [comment]
> @RogerPallares @raimonpv should syntax point to other edw folder or will /media/ml4c3/edw be overwritten?

Syntax updated

**Comment by erikr** [comment]
Getting an odd error:
```
2021-01-23 17:00:22 - INFO - tensorizer:177 - Tensorized data from MRN 123, CSN 456 into /home/erikr/icu-temp/results_temp/123.hd5.
2021-01-23 17:04:48 - ERROR - recipes:129 - [Errno 5] Input/output error
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/tensorizer.py", line 347, in _copy_hd5
    shutil.copy(source_path, destination_dir)
  File "/usr/lib/python3.8/shutil.py", line 409, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 271, in copyfile
    return dst
OSError: [Errno 5] Input/output error
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/erikr/ml4c3/ml4c3/recipes.py", line 69, in run
    tensorize_icu(args)
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/tensorizer.py", line 477, in tensorize
    copy_hd5(
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/tensorizer.py", line 333, in copy_hd5
    pool.starmap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
OSError: [Errno 5] Input/output error
2021-01-23 17:04:48 - INFO - recipes:136 - Executed tensorize_icu_no_edw_pull operation in 3913.08 sec
```

**Comment by erikr** [comment]
@StevenSong Can you try tensorizing my batch? I had a problem per above.

**Comment by StevenSong** [comment]
finished above, @RogerPallares or @epalto, do either of you need help?

**Comment by raimonpv** [comment]
I can help too

**Comment by RogerPallares** [comment]
I'm fine thanks! It'll be done by tonight/tomorrow morning

**Comment by epalto** [comment]
I'm fine too, thank you! it should finish by tomorrow morning

**Comment by RogerPallares** [comment]
Haven't you guys encountered this issue #1234 during tensorization? It happened to me once and first I thought it was only a file that was pulled incorrectly, but it kept happening to me for more files, so I'm gonna remove all those and re-pull them again.

**Comment by RogerPallares** [comment]
All files are stored in `/media/ml4c3/hd5_cabg_arrest`. I have just run the script `remove_unfinished_icu_hd5.py` to check for unfinished files and ~830 have been removed, probably because of #1234 and also if the process was suddenly stopped. Retensorizing those patients again. Do we want to maintain these files at `/media/ml4c3/hd5_cabg_arrest` or at `/media/ml4c3/hd5'?

**Comment by StevenSong** [comment]
> Haven't you guys encountered this issue #1234 during tensorization? It happened to me once and first I thought it was only a file that was pulled incorrectly, but it kept happening to me for more files, so I'm gonna remove all those and re-pull them again.

No, they never errored and I double checked the logs, all completed without any error

**Comment by StevenSong** [comment]
> All files are stored in `/media/ml4c3/hd5_cabg_arrest`. I have just run the script `remove_unfinished_icu_hd5.py` to check for unfinished files and ~830 have been removed, probably because of #1234

What are the criteria for `unfinished`? I have the logs for my tensorization runs and while there are warnings, none are what you saw in #1234. Could missing bedmaster data would result in an unfinished hd5?

**Comment by RogerPallares** [comment]
Unfinished criteria is based in a 2 flags that are stored once all edw and bedmaster data from a patient are tensorized, respectively. The script checks these 2 flags, in case there is no Bedmaster data, it only checks the flag related to EDW data. It also has an option to remove files without Bedmaster data, but I didn't set this argument now.

**Comment by StevenSong** [comment]
@RogerPallares could you take a look at these logs, did I miss something? https://www.dropbox.com/sh/nqanzeu9n07dsyt/AAB_61nR6XweEl-qiLHp3zOka?dl=0

**Comment by RogerPallares** [comment]
From the log file `log_2021-01-22_13-27.log` it looks like you tensorized without LM4 mounted. BM files weren't found, but they are matched at xref. Since all those patients have BM data (because it appears in xref), but hasn't been tensorized, then the flag for finished BM data is False and this is why they were removed by the script.

**Comment by StevenSong** [comment]
ah, okay ty for looking at those logs, that makes alot of sense, it seems like just my first tensorization run failed then, thats adt index 5600 to 6843 - i can rerun those or have you already started on those as well?

**Comment by RogerPallares** [comment]
Yes, no problem! I already ran the process, so don't worry, it should finish soon.

**Comment by erikr** [comment]
> it looks like you tensorized without LM4 mounted

Thanks to @raimonpv's work on https://github.com/aguirre-lab/ml4c3/pull/1231 this should no longer trouble us.

**Comment by RogerPallares** [comment]
All patients tensorized and stored in `/media/ml4c3/hd5_cabg_arrest`. However, considering issues #1258, we'll retensorize again, so I don't close the issue.
