### ISSUE TITLE
STS: assess distribution of age, sex, and ECG metadata by mortality status

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1155]

**Comment by erikr** [comment]
Getting error
```
2021-01-17 14:11:54 - INFO - explorations:1072 - Extracted 41701 tensors
2021-01-17 14:11:54 - INFO - datasets:337 - Stopped 10 explore workers.
2021-01-17 14:11:54 - INFO - explorations:1086 - Reorganized tensors into dataframe
2021-01-17 14:11:54 - INFO - explorations:1092 - Sorted tensors by patient ID
2021-01-17 14:11:54 - INFO - explorations:765 - Saved /home/erikr/dropbox/ecgnet-sts/explore-age-sex-metadata/label_distribution_all_all.csv
2021-01-17 14:11:54 - INFO - explorations:731 - Updated cross-reference counts for window (all) and title (all)
2021-01-17 14:11:54 - INFO - explorations:647 - Saved histogram of ecg_age_std_60_days_before_sts to /home/erikr/dropbox/ecgnet-sts/explore-age-sex-metadata/histogram_ecg_age_std_60_days_before_sts_all.pdf
/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py:664: RuntimeWarning: invalid value encountered in long_scalars
  stats["missing_fraction"] = stats["missing"] / stats["total"]
2021-01-17 14:11:55 - INFO - explorations:647 - Saved histogram of ecg_rate_std_md_60_days_before_sts to /home/erikr/dropbox/ecgnet-sts/explore-age-sex-metadata/histogram_ecg_rate_std_md_60_days_before_sts_all.pdf
/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py:664: RuntimeWarning: invalid value encountered in long_scalars
  stats["missing_fraction"] = stats["missing"] / stats["total"]
2021-01-17 14:11:56 - INFO - explorations:647 - Saved histogram of ecg_pr_std_md_60_days_before_sts to /home/erikr/dropbox/ecgnet-sts/explore-age-sex-metadata/histogram_ecg_pr_std_md_60_days_before_sts_all.pdf
/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py:664: RuntimeWarning: invalid value encountered in long_scalars
  stats["missing_fraction"] = stats["missing"] / stats["total"]
2021-01-17 14:11:57 - INFO - explorations:647 - Saved histogram of ecg_qt_std_md_60_days_before_sts to /home/erikr/dropbox/ecgnet-sts/explore-age-sex-metadata/histogram_ecg_qt_std_md_60_days_before_sts_all.pdf
/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py:664: RuntimeWarning: invalid value encountered in long_scalars
  stats["missing_fraction"] = stats["missing"] / stats["total"]
2021-01-17 14:11:58 - INFO - explorations:647 - Saved histogram of ecg_qrs_std_md_60_days_before_sts to /home/erikr/dropbox/ecgnet-sts/explore-age-sex-metadata/histogram_ecg_qrs_std_md_60_days_before_sts_all.pdf
/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py:664: RuntimeWarning: invalid value encountered in long_scalars
  stats["missing_fraction"] = stats["missing"] / stats["total"]
2021-01-17 14:11:59 - INFO - explorations:647 - Saved histogram of ecg_raxis_std_md_60_days_before_sts to /home/erikr/dropbox/ecgnet-sts/explore-age-sex-metadata/histogram_ecg_raxis_std_md_60_days_before_sts_all.pdf
/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py:664: RuntimeWarning: invalid value encountered in long_scalars
  stats["missing_fraction"] = stats["missing"] / stats["total"]
2021-01-17 14:11:59 - INFO - explorations:647 - Saved histogram of ecg_paxis_std_md_60_days_before_sts to /home/erikr/dropbox/ecgnet-sts/explore-age-sex-metadata/histogram_ecg_paxis_std_md_60_days_before_sts_all.pdf
/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py:664: RuntimeWarning: invalid value encountered in long_scalars
  stats["missing_fraction"] = stats["missing"] / stats["total"]
2021-01-17 14:12:00 - INFO - explorations:647 - Saved histogram of ecg_taxis_std_md_60_days_before_sts to /home/erikr/dropbox/ecgnet-sts/explore-age-sex-metadata/histogram_ecg_taxis_std_md_60_days_before_sts_all.pdf
/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py:664: RuntimeWarning: invalid value encountered in long_scalars
  stats["missing_fraction"] = stats["missing"] / stats["total"]
2021-01-17 14:12:00 - INFO - explorations:533 - all / union / continuous tmaps: saved summary stats to /home/erikr/dropbox/ecgnet-sts/explore-age-sex-metadata/stats_continuous_all_union.csv
2021-01-17 14:12:00 - ERROR - recipes:89 - division by zero
Traceback (most recent call last):
  File "/home/erikr/ml4c3/ml4c3/recipes.py", line 68, in run
    explore(args=args, disable_saving_output=args.explore_disable_saving_output)
  File "/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py", line 508, in explore
    stats = _calculate_summary_stats(
  File "/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py", line 668, in _calculate_summary_stats
    stats["fraction"] = num_key / len(df[key])
ZeroDivisionError: division by zero
2021-01-17 14:12:00 - INFO - recipes:95 - Executed explore operation in 467.71 sec
```

using this syntax
```PREFIX=$HOME/dropbox/sts-data
BOOTSTRAP=0
./scripts/run.sh $PWD/ml4c3/recipes.py explore \
--num_workers 10 \
--tensors     /storage/shared/ecg/mgh \
--tensors     $PREFIX/sts-mgh.csv sts \
--train_csv   $PREFIX/bootstraps-ecg/$BOOTSTRAP/train.csv \
--valid_csv   $PREFIX/bootstraps-ecg/$BOOTSTRAP/valid.csv \
--test_csv    $PREFIX/bootstraps-ecg/$BOOTSTRAP/test.csv \
--input_tensors \
    ecg_age_std_60_days_before_sts \
    ecg_sex_60_days_before_sts \
    ecg_rate_std_md_60_days_before_sts \
    ecg_pr_std_md_60_days_before_sts \
    ecg_qt_std_md_60_days_before_sts \
    ecg_qrs_std_md_60_days_before_sts \
    ecg_raxis_std_md_60_days_before_sts \
    ecg_paxis_std_md_60_days_before_sts \
    ecg_taxis_std_md_60_days_before_sts \
    atrial_fibrillation_60_days_before_sts \
    atrial_flutter_60_days_before_sts \
    ischemia_60_days_before_sts \
    mi_60_days_before_sts \
    rae_60_days_before_sts \
    lae_60_days_before_sts \
    lvh_60_days_before_sts \
    left_bundle_branch_block_60_days_before_sts \
    right_bundle_branch_block_60_days_before_sts \
    supraventricular_tachycardia_60_days_before_sts \
    normal_sinus_rhythm_60_days_before_sts \
    pacemaker_60_days_before_sts \
    atrial_paced_rhythm_60_days_before_sts \
    ventricular_tachycardia_60_days_before_sts \
    ventricular_fibrillation_60_days_before_sts \
    sts_death_60_days_after_ecg \
--explore_stratify_label \
    sts_death_60_days_after_ecg \
--output_folder $HOME/dropbox/ecgnet-sts/explore-age-sex-metadata
```

**Comment by erikr** [comment]
Cause of this problem identified. The union `_df` had `NaN` entries for the label column `sts_death_60_days_after_ecg`, resulting in `labels` list: `["all", 0.0, np.nan, 1.0]`.

The DataFrame returned by `_df[_df[args.explore_stratify_label] == label]` is empty if `label` is `NaN`. This is strange because `_df[_df[args.explore_stratify_label].isna()]` is not empty. The creators of numpy sought to make `np.nan == np.nan` return `False`, so they are to blame for what I and others think is counter-intuitive behavior.

I'll open a PR to fix.
