### ISSUE TITLE
Explore crashes if there is no intersection

### ISSUE THREAD

**Issue by raimonpv** [aguirre-lab/ml4c3#1213]
## Error message or warning

```
2021-01-25 13:50:58 - ERROR - recipes:129 - '<=' not supported between instances of 'str' and 'float'
Traceback (most recent call last):
  File "/home/rp416/repos/ml4c3/ml4c3/recipes.py", line 87, in run
    explore(args=args, disable_saving_output=args.explore_disable_saving_output)
  File "/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py", line 518, in explore
    stats = _calculate_summary_stats(
  File "/usr/local/lib/python3.8/dist-packages/ml4c3/explorations.py", line 698, in _calculate_summary_stats
    stats["min"] = df[key].min()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 11204, in min
    return NDFrame.min(self, axis, skipna, level, numeric_only, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 10709, in min
    return self._stat_function(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 10704, in _stat_function
    return self._reduce(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/series.py", line 4152, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/nanops.py", line 133, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/nanops.py", line 392, in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/nanops.py", line 975, in reduction
    result = getattr(values, meth)(axis)
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: '<=' not supported between instances of 'str' and 'float'
2021-01-25 13:50:58 - INFO - recipes:136 - Executed explore operation in 1597.03 sec
```

## Expected behavior
This happens when there is no intersection of MRNs having all the tensors.

## Possible solution
If there is no intersection it does not crash.
Also, it will be great if it returns a .csv file where each row corresponds to a MRN/input file and each column if it returned a valid tensor or not (True or False) for the corresponding tensor map.

## Steps to reproduce
1. Run `~/dropbox/cardiac-arrest/scripts/explore.sh`

**Comment by erikr** [comment]
`explore` docs need updating.

> Also, it will be great if it returns a .csv file where each row corresponds to a MRN/input file and each column if it returned a valid tensor or not (True or False) for the corresponding tensor map.

Should be enabled by
https://github.com/aguirre-lab/ml4c3/blob/ded98fac974f39aefe5e5383aa26c7a76cb2288d/ml4c3/arguments.py#L839-L843

and checking output in `tensors_union_all.csv`.

**Comment by StevenSong** [comment]
@erikr lol I feel like this is something we've silently ignored the past few months, ty @raimonpv
