### ISSUE TITLE
Empty EDW tables

### ISSUE THREAD

**Issue by RogerPallares** [aguirre-lab/ml4c3#1234]
## Error message or warning
```
2021-01-26 16:49:40 - ERROR - tensorizer:183 - Tensorization failed for MRN xxxx with CSNs {'xxxx': ['/home/rp415/icu-temp/bedmaster_temp/BLK08_890-1482380194_0_v4.mat']}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/tensorizer.py", line 166, in _main_write
    self._write_bedmaster_alarms_data(
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/tensorizer.py", line 234, in _write_bedmaster_alarms_data
    reader = BedmasterAlarmsReader(alarms_path, edw_path, mrn, visit_id, adt)
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/readers.py", line 1381, in __init__
    self.alarms_dfs = self._get_alarms_dfs()
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/readers.py", line 1437, in _get_alarms_dfs
    movement_df = pd.read_csv(self.move_file)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers.py", line 605, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers.py", line 814, in __init__
    self._engine = self._make_engine(self.engine)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers.py", line 1045, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers.py", line 1893, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

## Expected behavior
Even EDW tables are empty, they must have the columns.

## Possible solution
Find and delete all EDW tables without columns, pull those tables again.

## Steps to reproduce
1. Run tensorice_icu

**Comment by RogerPallares** [comment]
Encountered all this empty tables (without columns):
```
File /media/ml4c3/edw-cabg-arrest-cleaned/503173/3192958503/demographics.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/512657/3182936051/transfusions.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/443828/3201399984/diagnosis.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/749313/3153826551/procedures.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/731864/3328175341/movements.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/655238/3133178205/medications.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/499248/3212534938/surgical-history.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/727486/3324043494/movements.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/599899/3272304157/surgery.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/540955/3147867789/transfusions.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/464124/3309957893/flowsheet.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/734117/3244895544/procedures.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/748865/3145111904/procedures.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/672730/3204606538/procedures.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/572185/3223025365/surgery.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/729554/3142292641/movements.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/582958/3229640832/surgery.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/596436/3140254013/movements.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/512812/3325124001/surgery.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/712064/3114557772/procedures.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/564883/3126971833/transfusions.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/494182/3227460553/medical-history.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/674992/3158245982/procedures.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/593821/3238113922/movements.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/612956/3116389830/surgery.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/459562/3167530659/admission-vitals.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/722909/3256184152/movements.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/507934/3128166449/surgery.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/696002/3134671992/movements.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/760713/3181317027/events.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/538873/3287350816/surgery.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/670472/3178051295/movements.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/562614/3188828273/movements.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/585865/3142004163/surgery.csv removed for being empty.
File /media/ml4c3/edw-cabg-arrest-cleaned/475868/3168751381/surgical-history.csv removed for being empty.
Removed empty tables (.csv) in 440.74 seconds
```
