### ISSUE TITLE
Hyperoptimize requires formatting conv_x as a list, even if just one value

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1373]
## Error message or warning
```
2021-02-15 17:04:35 - ERROR - hyperoptimizers:45 - object of type 'int' has no len()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ml4c3/hyperoptimizers.py", line 43, in train_model_worker
    performance_metrics = train_model(args)
  File "/usr/local/lib/python3.8/dist-packages/ml4c3/recipes.py", line 194, in train_model
    model = make_model(args)
  File "/usr/local/lib/python3.8/dist-packages/ml4c3/models.py", line 260, in make_model
    model = make_multimodal_multitask_model(**args.__dict__)
  File "/usr/local/lib/python3.8/dist-packages/ml4c3/models.py", line 570, in make_multimodal_multitask_model
    conv_x = _repeat_dimension(
  File "/usr/local/lib/python3.8/dist-packages/ml4c3/models.py", line 1519, in _repeat_dimension
    if len(dim) != num_filters_needed:
TypeError: object of type 'int' has no len()
```

## Expected behavior
no error

## Possible solution
when parsing args in `hyperoptimize`, if `conv_x` is found and it is an int, cast it to a list

## Steps to reproduce
call `hyperoptimize`

```bash
PREFIX=/storage/shared/sts-data
RESULTS=$HOME
CONFIG_PATH=$HOME

BOOTSTRAP=0

./scripts/run.sh -d 0,1,2,3,4,5 $PWD/ml4c3/recipes.py hyperoptimize \
--max_evals 10 \
--hyperoptimize_config_file $CONFIG_PATH/hyperoptimize-voltage-simple.json \
--num_workers 6 \
--tensors     /storage/shared/ecg/mgh \
--tensors     $PREFIX/mgh.csv sts \
--train_csv   $PREFIX/bootstraps-intersect-ecg-age-sex-metadata-newest/$BOOTSTRAP/train.csv \
--valid_csv   $PREFIX/bootstraps-intersect-ecg-age-sex-metadata-newest/$BOOTSTRAP/valid.csv \
--test_csv    $PREFIX/bootstraps-intersect-ecg-age-sex-metadata-newest/$BOOTSTRAP/test.csv \
--input_tensors \
    ecg_2500_zscore_pop_60_days_before_sts \
--filter_tensors \
    ecg_age_60_days_before_sts \
    ecg_sex_60_days_before_sts \
    ecg_rate_md_60_days_before_sts \
    ecg_pr_md_60_days_before_sts \
    ecg_qt_md_60_days_before_sts \
    ecg_qrs_md_60_days_before_sts \
    ecg_raxis_md_60_days_before_sts \
    ecg_paxis_md_60_days_before_sts \
    ecg_taxis_md_60_days_before_sts \
--output_tensors \
    sts_death_60_days_after_ecg \
    sts_stroke_60_days_after_ecg \
    sts_renal_failure_60_days_after_ecg \
    sts_prolonged_ventilation_60_days_after_ecg \
    sts_dsw_infection_60_days_after_ecg \
    sts_reoperation_60_days_after_ecg \
    sts_long_stay_60_days_after_ecg \
--samples_per_patient 1 \
--conv_blocks 32 \
--conv_block_size 1 \
--conv_block_layer_order convolution normalization activation dropout \
--dense_block_layer_order convolution normalization activation dropout \
--pool_type max \
--bottleneck_type flatten_restructure \
--learning_rate_patience 8 \
--learning_rate_reduction 0.5 \
--patience 24 \
--epochs 1024 \
--batch_size 256 \
--output_folder $RESULTS/hyperoptimize/voltage-newest-v01
```

using this config file that only has a single value for `conv_x`:
```json
{
    "recipe": ["train"],
    "optimizer": ["sgd", "adam", "radam", "adamw"],
    "learning_rate": [0.0001, 0.0005, 0.001],
    "dense_dropout": [0.1, 0.25, 0.3, 0.4, 0.5],
    "conv_x": [30],
    "spatial_dropout": [0.1, 0.2, 0.3, 0.4],
    "dense_blocks": [
        [12, 24, 48, 96],
        [12, 24, 48, 96, 192]
    ],
    "dense_block_size": [2, 3, 4],
    "pool_x": [2, 3],
    "dense_layers": [
        [64, 32],
        [64, 16],
        [32, 16],
        [64, 32, 16]
    ]
}
```

**Comment by StevenSong** [comment]
Some one off cases like this are probably convenient to add but it is documented that the types need to match: https://github.com/aguirre-lab/ml4c3/wiki/Hyperoptimization#hyperoptimize-configuration-file

Though a question, what happens if in the config.json file, there's `'conv_x': [32, 16]`? Does that mean you want to hyperoptimize over 2 settings of conv_x for all conv layers? or that each the model gets alternating conv layers of size 32/16? both are possible though the latter is more unlikely - for this specific case, it's probably fine to encode some heuristics but hard to generalize

**Comment by erikr** [comment]
I was getting annoyed at the extra formatting burden, but your example makes me realize the current setup is good.
